# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '59' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 59

  pod 'lottie-ios'

  target '59Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '59UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
