# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '17' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 17

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'MessageKit'
  pod 'Alamofire'

end
