# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '62' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 62

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target '62Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '62UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
